name: 'Issue2md'
author: 'Akira Masuda (go-zen-chu)'
description: 'Converting GitHub issue to markdown'
inputs:
  # required
  export-dir:
    description: 'Which directory inside your repository to export markdown. Default is / (repository root)'
    required: true
    default: '/'
  issue-url:
    description: 'GitHub issue URL'
    required: true
  # optional
  debug:
    description: 'Run issue2md with debug mode'
    default: false 
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - -export-dir
    - ${{ inputs.export-dir }}
    - -issue-url
    - ${{ inputs.issue-url }}
    - -debug
    - ${{ inputs.debug }} 

