name: "issue2md"
author: "Akira Masuda (go-zen-chu)"
description: "Converting GitHub issue to markdown"
inputs:
  # required
  github-token:
    description: "GitHub token to read/write issue & repository"
    required: true
  issue-url:
    description: "GitHub issue URL"
    required: true
  export-dir:
    description: "A directory in your repository to export markdown. Default is `.` (repository root)"
    required: false
    default: "."
  # optional
  debug:
    description: "Run issue2md with debug mode"
    default: "false"
  check-dups:
    description: "Find duplicate issueURL markdowns exists"
    default: "false"
  auto-commit:
    description: "Automatically commit changes if markdown files are created or updated"
    default: "false"
  auto-push:
    description: "Automatically push changes to remote (requires auto-commit)"
    default: "false"
runs:
  using: "docker"
  image: "docker://amasuda/issue2md:latest"
  args:
    - -github-token=${{ inputs.github-token }}
    - -issue-url=${{ inputs.issue-url }}
    - -export-dir=${{ inputs.export-dir }}
    - -debug=${{ inputs.debug }}
    - -check-dups=${{ inputs.check-dups }}
    - -auto-commit=${{ inputs.auto-commit }}
    - -auto-push=${{ inputs.auto-push }}
branding:
  icon: "book"
  color: "blue"
