name: issue2md
on:
  issues:
    types:
      - closed
jobs:
  issue2md:
    runs-on: ubuntu-latest
    name: convert closed issue to markdown
    # when state_reason is `not_planned` this action does not proceed
    if: ${{ github.event.issue.state_reason == 'completed' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Convert issue to markdown
        uses: go-zen-chu/issue2md@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-url: ${{ github.event.issue.html_url }}
          # By default, this action stores markdown to repository root. If you want to change export dir, make directory and change setting below.
          #export-dir: ./issues
      - name: Check diff
        id: diff
        run: |
          git add -N .
          # it gets exit code 0 when no diff found
          git diff --name-only --exit-code
        continue-on-error: true
      - name: Push to main branch if any updates exist
        if: steps.diff.outcome == 'failure'
        run: |
          set -e
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git diff
          git diff-index HEAD
          git add --all
          git commit -m "[skip ci] [GitHub Action] Update automatically"
          git push
      # If you use slack, uncomment step below to POST failure notice when issue2md failed (requires SLACK_WEBHOOK_URL)
      # - name: Send custom JSON data to Slack when issue2md failed
      #   if: failure() && steps.issue2md.outcome == 'failure'
      #   id: slack
      #   uses: slackapi/slack-github-action@v1.23.0
      #   with:
      #     payload: |
      #       {
      #         "text": ":warning: GitHub Action build result: ${{ job.status }}",
      #         "blocks": [
      #           {
      #             "type": "section",
      #             "text": {
      #               "type": "mrkdwn",
      #               "text": "GitHub Action build result: ${{ job.status }}\nActions URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs/${{ github.job }}"
      #             }
      #           }
      #         ]
      #       }
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      #     SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
