name: issue2md
on:
  issues:
    types:
      - closed

jobs:
  convert_issue2md:
    runs-on: ubuntu-latest
    name: convert closed issue to markdown
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true
      - name: Build binary
        run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -v -o issue2md cmd/issue2md/*.go
      - name: (Private) issue2md step
        uses: ./ # Uses an action in the root directory
        id: issue2md
        env:
          ISSUE2MD_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          debug: true
          export-dir: issues
          issue-url: ${{ github.event.issue.html_url }}
      - name: commit if any updates exists
        run: |
            set -x
            if git diff-index --quiet HEAD --; then
                echo "git diff exit code $?. No changes"
            else
                echo "git diff exit code $?. Update detected"
                set -e
                git config --local user.email "action@github.com"
                git config --local user.name "GitHub Action"
                git diff
                git diff-index HEAD
                git add --all
                git commit -m "[GitHub Action] Update automatically"
                git push
            fi
