name: issue2md
on:
  issues:
    types:
      - closed
jobs:
  issue2md:
    runs-on: ubuntu-latest
    name: Convert closed issue to markdown with published action
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Convert issue to markdown
        uses: go-zen-chu/issue2md@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-url: ${{ github.event.issue.html_url }}
          # By default, this action stores markdown to repository root. If you want to change export dir, make directory and change setting below.
          export-dir: ./issues
      - name: Push to main branch if any updates exists
        run: |
            set -x
            gdiff=$(git diff)
            if [[ -z $gdiff ]]; then
                echo "No changes"
            else
                echo "Update detected"
                set -e
                git config --local user.email "action@github.com"
                git config --local user.name "GitHub Action"
                git diff
                git diff-index HEAD
                git add --all
                git commit -m "[skip ci] [GitHub Action] Update automatically"
                git push
            fi
