name: issue2md
on:
  issues:
    types:
      - closed

jobs:
  convert_issue2md:
    runs-on: ubuntu-latest
    name: convert closed issue to markdown
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true
      - name: Build binary
        run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -v -o issue2md cmd/issue2md/main.go
      - name: (Private) issue2md step
        uses: ./ # Uses an action in the root directory
        id: issue2md
        with:
          debug: true
          export-dir: issues
          issue-number: ${{ github.event.issue.number }}
          issue-title: ${{ github.event.issue.title }}
          issue-labels: ${{ github.event.issue.labels }}
