# actual working sample for dogfooding using latest issue2md
name: issue2md-check-dups
on:
  - push
jobs:
  issue2md:
    runs-on: ubuntu-latest
    name: Check same issueURL markdown exists in export-dir
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Convert issue to markdown
        uses: go-zen-chu/issue2md@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-url: ${{ github.event.issue.html_url }}
          # By default, this action stores markdown to repository root. If you want to change export dir, make directory and change setting below.
          export-dir: ./issues
      - name: Send custom JSON data to Slack when issue2md failed
        if: failure()
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "text": ":warning: GitHub Action build result: ${{ job.status }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "GitHub Action build result: ${{ job.status }}\nActions URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                  }
                }
              ]
            }
        env:
          # currently, it is set to my personal slack channel
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
