# actual working sample for dogfooding using latest issue2md
name: issue2md-check-dups
on:
  push:
    branches:
      - main
jobs:
  issue2md:
    runs-on: ubuntu-latest
    name: Check same issueURL markdown exists in export-dir
    steps:
      - uses: actions/checkout@v7

      - name: Check and list duplicated issue markdowns
        uses: go-zen-chu/issue2md@main
        with:
          # By default, this action stores markdown to repository root. If you want to change export dir, make directory and change setting below.
          export-dir: ./issues
          check-dups: true
